# Generated by Django 4.2.3 on 2023-09-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheSecondDjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='name_product',
        ),
        migrations.AddField(
            model_name='orders',
            name='name_product',
            field=models.ManyToManyField(to='TheSecondDjango.products'),
        ),
    ]
